<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Logo' => '',
  'Two passwords do not match' => '',
  'Username already exists' => '',
  'Accept' => '接受',
  'Activity manager' => '活动管理',
  'Administrator manager' => '管理员管理',
  'Agreement' => '协议',
  'Base information' => '基本信息',
  'Bluetooth base station' => '蓝牙基站',
  'Category' => '分类',
  'Century' => '年代',
  'Client user' => '客户端用户',
  'Console' => '控制台',
  'Create' => '创建',
  'Delete' => '删除',
  'Delete Failure' => '删除失败',
  'Delete Success' => '删除成功',
  'Description' => '描述',
  'Disable' => '禁用',
  'Disable failure' => '禁用失败',
  'Disable push' => '禁用推送',
  'Disable push failure' => '禁用推送失败',
  'Disable push success' => '禁用推送成功',
  'Disable success' => '禁用成功',
  'Edit' => '编辑',
  'Email' => '邮箱',
  'Email send failure.' => '邮件发送失败',
  'Email send success.' => '邮件发送成功',
  'Enable' => '启用',
  'Enable push' => '启用推送',
  'Enable push failure' => '启用推送失败',
  'Enable push success' => '启用推送成功',
  'Female' => '女',
  'Forgot password' => '忘记密码',
  'Home' => '首页',
  'Id' => 'Id',
  'Illegal request' => '非法请求',
  'Log manager' => '日志管理',
  'Login' => '登录',
  'Male' => '男',
  'Member' => '会员',
  'Merchant' => '商户',
  'Merchant register' => '商户注册',
  'Merchant shop_manager' => '商铺管理',
  'Mobile' => '手机号',
  'Mobile format error.' => '手机号格式错误',
  'Name' => '名称',
  'New password' => '新密码',
  'Normal' => '正常',
  'Other' => '其他',
  'Password' => '密码',
  'Password invalid' => '密码无效',
  'Password is not correct' => '密码不正确',
  'Pelase input email' => '请输入邮箱',
  'Product' => '商品',
  'Register' => '注册',
  'Remember me' => '记住我',
  'Repeat password' => '重复密码',
  'Reset' => '重置',
  'Reset password' => '重置密码',
  'Restore failure' => '恢复失败',
  'Restore success' => '恢复成功',
  'Return login' => '返回登录',
  'Save' => '保存',
  'Sex' => '性别',
  'Status' => '状态',
  'System manager' => '系统管理',
  'System settings' => '系统设置',
  'Unknown' => '保密',
  'User manaer' => '用户管理',
  'User status invalid' => '用户状态无效',
  'Username' => '用户名',
  'Username invalid' => '用户名无效',
  'Username is invalid' => '用户名无效',
  'century' => '年代',
);
