<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Accept' => '接受',
  'Activity manager' => '活动管理',
  'Agreement' => '协议',
  'Delete Failure' => '删除失败',
  'Delete Success' => '删除成功',
  'Disable Failure' => '禁用失败',
  'Disable Success' => '禁用成功',
  'Email' => '邮箱',
  'Forgot password' => '忘记密码',
  'Illegal request' => '非法请求',
  'Login' => '登录',
  'Merchant manager' => '商户管理',
  'Merchant shop_manager' => '商铺管理',
  'Merchant register' => '商户注册',
  'Name' => '名称',
  'Password' => '密码',
  'Register' => '注册',
  'Remember me' => '记住我',
  'Repeat password' => '重复密码',
  'Reset' => '重置',
  'Restore Failure' => '恢复失败',
  'Restore Success' => '恢复成功',
  'Return login' => '返回登录',
  'User manaer' => '用户管理',
  'Username' => '用户名',
);
