<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  ' is already taken.' => '',
  ' is not set.' => '',
  'Advertisement is no exist' => '',
  'Illegal identity' => '',
  'Illegal request' => '',
  'Illegal request.' => '',
  'Merchant is no exist' => '',
  'Not editable' => '',
  'Please use GET method' => '',
  'Please use GET method to get data.' => '',
  'Please use POST method' => '',
  'Please use POST method to submit data.' => '',
  'Please use POST method to submit data. to submit data.' => '',
  'Token not exist' => '',
  'Token not set' => '',
  'User is no exist' => '',
  ' is not correct' => ' 不正确',
  ' is not set' => ' 未设置',
  'Repeat Request' => '重复请求',
  'Station Illegal' => '基站无效',
  'Token has expired' => 'Token已过期',
  'Token is not exist' => 'Token不存在',
);
