<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Delete Failure' => '@@删除失败@@',
  'Edit Success' => '@@@@',
  'Param Error' => '@@参数错误@@',
  'Add' => '添加',
  'Choose a picture' => '选择一张图片',
  'Create' => '创建',
  'Create Failure' => '创建失败',
  'Create Success' => '创建成功',
  'Delete' => '删除',
  'Delete Success' => '删除成功',
  'Edit' => '编辑',
  'Illegal Operation' => '非法操作',
  'Modify Failure' => '修改失败',
  'Modify Success' => '修改成功',
  'Number' => '编号',
  'Operate' => '操作',
  'Pelease select a date' => '请选择有效日期',
  'Picture' => '图片',
  'Price' => '金额',
  'Reset' => '重置',
  'Select' => '查询',
  'Submit' => '提交',
  'Total' => '总量',
);
