<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Create Failure' => '',
  'Modify Failure' => '',
  'Edit Failure' => '@@@@',
  'Product Manager' => '@@商品管理@@',
  'Stamp Edit' => '@@编辑印花@@',
  'Coupon Create' => '添加优惠券',
  'Coupon List' => '优惠券列表',
  'Coupon Manager' => '优惠券管理',
  'Coupon Name' => '优惠券名称',
  'Coupon total' => '总量',
  'Coupon used' => '使用量',
  'Coupon use'=>"优惠券使用",
  'Coupon Code'=>"优惠券码",
  'Coupon validity end' => '有效期结束时间',
  'Coupon validity start' => '有效期开始时间',
  'Main' => '总店',
  'Only' => '独家',
  'Pelase choose  a shop' => '请选择一个店铺',
  'Pelase input coupon name' => '请输入优惠券名称',
  'Pelase input coupon price' => '请输入优惠券价格',
  'Pelase input coupon total' => '请输入优惠券数量',
  'Pelase input shop address' => '请输入店铺地址',
  'Pelase input shop floor' => '请输入商铺楼层号',
  'Pelase input shop market place' => '请输入商铺所在商场',
  'Pelase input shop name' => '请输入商铺名',
  'Pelase input shop owner' => '请输入店主名',
  'Pelase input shop url' => '请输入店铺网址',
  'Pelase input stamp name' => '请输入印花名称',
  'Pelase input stamp total' => '请输入印花数量',
  'Pelase input telephone' => '请输入联系电话',
  'Product Create' => '添加商品',
  'Product List' => '商品列表',
  'Shop Address' => '店铺地址',
  'Shop Category' => '商铺行业',
  'Shop Create' => '创建商铺',
  'Shop District' => '商圈',
  'Shop Floor' => '楼层号',
  'Shop List' => '商铺列表',
  'Shop Manager' => '商铺管理',
  'Shop Market Place' => '所在商场',
  'Shop Name' => '商铺名',
  'Shop Owner' => '店主名',
  'Shop URL' => '商铺网址',
  'Stamp Create' => '创建印花',
  'Stamp List' => '印花列表',
  'Stamp Manager' => '印花管理',
  'Stamp Name' => '印花名称',
  'Telephone' => '联系电话',
  "Not in validity"=>"不在有效期内",
  "Is in validity"=>"是否在有效期",
  "In validity"=>"在有效期内",
);
