<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Station Create' => '@@创建基站@@',
  'Pelase input positionX' => '请输入设备坐标X',
  'Pelase input positionY' => '请输入设备坐标Y',
  'Pelase input station name' => '请输入设备名称',
  'Pelase input station uuid' => '请输入设备唯一标识',
  'Shop' => '绑定商铺',
  'Station Disabled' => '设备禁用',
  'Station List' => '基站列表',
  'Station Manager' => '基站管理',
  'Station Name' => '设备名称',
  'Station UUID' => '设备标识',
  'Station add to ads' => '添加到基站广告列表',
  'Station ads edit' => '基站广告编辑',
  'Station ads list' => '基站广告列表',
  'positionX' => '定位坐标X',
  'positionY' => '定位坐标Y',
);
