<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Accept' => '',
  'Activity manager' => '',
  'Agreement' => '',
  'Delete Failure' => '',
  'Delete Success' => '',
  'Disable Failure' => '',
  'Disable Success' => '',
  'Email' => '',
  'Forgot password' => '',
  'Illegal request' => '',
  'Login' => '',
  'Merchant manager' => '',
  'Merchant register' => '',
  'Name' => '',
  'Password' => '',
  'Register' => '',
  'Remember me' => '',
  'Repeat password' => '',
  'Reset' => '',
  'Restore Failure' => '',
  'Restore Success' => '',
  'Return login' => '',
  'User manaer' => '',
  'Username' => '',
  'Name no set' => '@@@@',
  'Newpassword no set' => '@@@@',
  'Password no set' => '@@@@',
  'Please use POST' => '@@@@',
  'Username no set' => '@@@@',
);
