<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Create success.' => '',
  'Delete failure.' => '',
  'Delete success.' => '',
  'Illegal request.' => '',
  'Unapproved' => '',
  'Add' => '@@添加@@',
  'Delete' => '@@刪除@@',
  'Delete Failure' => '@@刪除失敗@@',
  'Edit Success' => '@@@@',
  'Param Error' => '@@參數錯誤@@',
  'Unapprove' => '@@審核未通過@@',
  'Approved' => '審核通過',
  'Approveding' => '待審核',
  'Choose a picture' => '選擇壹張圖片',
  'Create' => '創建',
  'Create Failure' => '創建失敗',
  'Create Success' => '創建成功',
  'Delete Success' => '刪除成功',
  'Edit' => '編輯',
  'Illegal Operation' => '非法操作',
  'Intro' => '簡介',
  'Modify Failure' => '修改失敗',
  'Modify Success' => '修改成功',
  'Number' => '編號',
  'Operate' => '操作',
  'Pelease select a date' => '請選擇有效日期',
  'Picture' => '圖片',
  'Price' => '金額',
  'Reset' => '重置',
  'Select' => '查詢',
  'Submit' => '提交',
  'Success' => '操作成功',
  'Total' => '總量',
  'status' => '狀態',
);
