<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Add push' => '',
  'Add station' => '',
  'Apply to shops' => '',
  'Coupon Code' => '',
  'Coupon Create' => '',
  'Coupon List' => '',
  'Coupon total' => '',
  'Coupon use' => '',
  'Coupon used' => '',
  'Coupon validity end' => '',
  'Coupon validity start' => '',
  'Coupons expired' => '',
  'Create Failure' => '',
  'Create account' => '',
  'In validity' => '',
  'Is in validity' => '',
  'Main' => '',
  'Modify Failure' => '',
  'Not in validity' => '',
  'Only' => '',
  'Pelase choose  a shop' => '',
  'Pelase input coupon name' => '',
  'Pelase input coupon price' => '',
  'Pelase input coupon total' => '',
  'Pelase input discount' => '',
  'Pelase input price' => '',
  'Pelase input shop address' => '',
  'Pelase input shop floor' => '',
  'Pelase input shop market place' => '',
  'Pelase input shop name' => '',
  'Pelase input shop owner' => '',
  'Pelase input shop url' => '',
  'Pelase input stamp name' => '',
  'Pelase input stamp total' => '',
  'Pelase input telephone' => '',
  'Pelease input product intro' => '',
  'Pelease input product name' => '',
  'Price' => '',
  'Product Create' => '',
  'Product List' => '',
  'Product Manager' => '',
  'Product edit' => '',
  'Product intro' => '',
  'Product name' => '',
  'Release people' => '',
  'Shop Address' => '',
  'Shop Category' => '',
  'Shop Create' => '',
  'Shop District' => '',
  'Shop Edit' => '',
  'Shop Floor' => '',
  'Shop Market Place' => '',
  'Shop Owner' => '',
  'Shop URL' => '',
  'Coupon Manager' => '優惠券管理',
  'Coupon Name' => '名稱',
  'Shop List' => '列表',
  'Shop Manager' => '店鋪管理',
  'Shop Name' => '名稱',
  'Stamp Create' => '創建',
  'Stamp List' => '列表',
  'Stamp Manager' => '印花管理',
  'Stamp Name' => '名稱',
  'Telephone' => '電話',
  'discount' => '折扣',
);
