<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Create Failure' => '',
  'Modify Failure' => '',
  'Coupon Create' => '添加優惠券',
  'Edit Failure' => '',
  'Product Create' => '添加商品',
  'Product List' => '商品列表',
  'Product Manager' => '商品管理',
  'Product edit' => '商品編輯',
  'Shop Create' => '創建商鋪',
  'Shop Edit' => '商鋪信息編輯',
  'Shop List' => '商鋪列表',
  'Stamp Create' => '創建印花',
  'Stamp Edit' => '編輯印花',
  'Stamp List' => '印花列表',
  'Add push' => '添加到人工推送',
  'Add station' => '添加藍牙基站',
  'Apply to shops' => '適用商鋪',
  'Coupon Code' => '優惠券碼',
  'Coupon List' => '優惠券列表',
  'Coupon Manager' => '優惠券管理',
  'Coupon Name' => '優惠券名稱',
  'Coupon total' => '總量',
  'Coupon use' => '優惠券使用',
  'Coupon used' => '使用量',
  'Coupon validity end' => '有效期結束時間',
  'Coupon validity start' => '有效期開始時間',
  'Coupons expired' => '優惠券已過期',
  'Create account' => '開通分店賬戶',
  'In validity' => '在有效期內',
  'Is in validity' => '是否在有效期',
  'Main' => '總店',
  'Not in validity' => '不在有效期內',
  'Only' => '獨家',
  'Pelase choose  a shop' => '請選擇壹個店鋪',
  'Pelase choose a shop' => '請為該商品至少關聯壹個商鋪',
  'Pelase input coupon name' => '請輸入優惠券名稱',
  'Pelase input coupon price' => '請輸入優惠券價格',
  'Pelase input coupon total' => '請輸入優惠券數量',
  'Pelase input discount' => '請輸入折扣',
  'Pelase input price' => '請輸入價格',
  'Pelase input shop address' => '請輸入店鋪地址',
  'Pelase input shop floor' => '請輸入商鋪樓層號',
  'Pelase input shop market place' => '請輸入商鋪所在商場',
  'Pelase input shop name' => '請輸入商鋪名',
  'Pelase input shop owner' => '請輸入店主名',
  'Pelase input shop url' => '請輸入店鋪網址',
  'Pelase input stamp name' => '請輸入印花名稱',
  'Pelase input stamp total' => '請輸入印花數量',
  'Pelase input telephone' => '請輸入聯系電話',
  'Pelease input product intro' => '請輸入商品簡介',
  'Pelease input product name' => '請輸入商品名稱',
  'Price' => '價格',
  'Product intro' => '商品簡介',
  'Product name' => '商品名稱',
  'Release people' => '發布人',
  'Shop Address' => '店鋪地址',
  'Shop Category' => '商鋪行業',
  'Shop District' => '商圈',
  'Shop Floor' => '樓層號',
  'Shop Manager' => '商鋪管理',
  'Shop Market Place' => '所在商場',
  'Shop Name' => '商鋪名',
  'Shop Owner' => '店主名',
  'Shop URL' => '商鋪網址',
  'Stamp Manager' => '印花管理',
  'Stamp Name' => '印花名稱',
  'Telephone' => '聯系電話',
  'discount' => '折扣',
);
