<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Coupon Create' => '',
  'Coupon List' => '',
  'Coupon Manager' => '',
  'Coupon Name' => '',
  'Coupon total' => '',
  'Coupon used' => '',
  'Coupon validity end' => '',
  'Coupon validity start' => '',
  'Create Failure' => '',
  'Edit Failure' => '',
  'Main' => '',
  'Only' => '',
  'Pelase choose  a shop' => '',
  'Pelase input coupon name' => '',
  'Pelase input coupon price' => '',
  'Pelase input coupon total' => '',
  'Pelase input shop address' => '',
  'Pelase input shop floor' => '',
  'Pelase input shop market place' => '',
  'Pelase input shop name' => '',
  'Pelase input shop owner' => '',
  'Pelase input shop url' => '',
  'Pelase input telephone' => '',
  'Product Create' => '',
  'Product List' => '',
  'Shop Address' => '',
  'Shop Category' => '',
  'Shop Create' => '',
  'Shop District' => '',
  'Shop Floor' => '',
  'Shop List' => '',
  'Shop Manager' => '',
  'Shop Market Place' => '',
  'Shop Name' => '',
  'Shop Owner' => '',
  'Shop URL' => '',
  'Telephone' => '',
);
