<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'Pelase input all' => '',
  'Station UUID is not only' => '',
  'Station Create' => '@@創建基站@@',
  'Pelase input positionX' => '請輸入設備坐標X',
  'Pelase input positionY' => '請輸入設備坐標Y',
  'Pelase input station name' => '請輸入設備名稱',
  'Pelase input station uuid' => '請輸入設備唯壹標識',
  'Shop' => '綁定商鋪',
  'Station Disabled' => '設備禁用',
  'Station List' => '基站列表',
  'Station Manager' => '基站管理',
  'Station Name' => '設備名稱',
  'Station UUID' => '設備標識',
  'Station add to ads' => '添加到基站廣告列表',
  'Station ads edit' => '基站廣告編輯',
  'Station ads list' => '基站廣告列表',
  'positionX' => '定位坐標X',
  'positionY' => '定位坐標Y',
);
